# Cloudflare Workers configuration for Treekit OAuth

name = "treekit-oauth"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Routes - this will handle requests to gettreekit.com/server/api/oauth/token
[[routes]]
pattern = "gettreekit.com/server/api/oauth/token"
zone_name = "gettreekit.com"

[[routes]]
pattern = "www.gettreekit.com/server/api/oauth/token"
zone_name = "gettreekit.com"

# Environment variables (set these in Cloudflare dashboard)
[env.production.vars]
# FIGMA_CLIENT_SECRET will be set via dashboard for security

# Optional: Custom domain setup
# [env.production]
# routes = [
#   { pattern = "gettreekit.com/api/*", zone_name = "gettreekit.com" }
# ]